### PR TITLE
Issue 103: Updated Plugin code with Android Gradle Plugin 3.6 compati…

### PR DESCRIPTION
**Pull request by DDeg**
Fixes for https://github.com/Archinamon/android-gradle-aspectj/issues/103 (Android Gradle plugin 3.6 compatibility).

### CODE REVIEW

**Comment by nisrulz** [comment]
@DDeg I can't make the project in your branch build. Did you have any pointers what I could be doing wrong?

**Comment by DDeg** [comment]
I'll upload local build to issue ticket for temporary usage, until 3.6 plugin support will not be ready.

**Comment by DDeg** [comment]
@Archinamon can you please review pull-request and build new release, if all is OK. Thanks.

**Comment by Archinamon** [comment]
Thanks! Will make build in a few hours!

**Pull request merged**
